version: '3.8'

services:
  woox-pro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: woox-frontend
    ports:
      - "8099:80"
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
